### ISSUE TITLE
cannot recursively call into `Core`

### ISSUE THREAD

**Issue by 5chdn** [goerli/parity-goerli#33]
- **Parity Ethereum version**: 2.3.0-nightly-a0616cfa5-20181225/x86_64-linux-gnu/rustc1.31.1 a0616cfa5
- **Operating system**: Arch Linux
- **Installation**: built from source
- **Fully synchronized**: no
- **Network**: ethereum, ropsten
- **Restarted**: no

```
~/.opt/parity-goerli/target/release master
❯ ./parity --no-warp
2018-12-25 14:40:38  Starting Parity-Ethereum/v2.3.0-nightly-a0616cfa5-20181225/x86_64-linux-gnu/rustc1.31.1
2018-12-25 14:40:38  Keys path /home/user/.local/share/io.parity.ethereum/keys/ethereum
2018-12-25 14:40:38  DB path /home/user/.local/share/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d
2018-12-25 14:40:38  State DB configuration: fast
2018-12-25 14:40:38  Operating mode: active
2018-12-25 14:40:38  Configured for Foundation using Ethash engine


====================

stack backtrace:
   0:     0x555f076978cd - backtrace::backtrace::trace::h6a895d5d279a8d2f
   1:     0x555f07696ae2 - <backtrace::capture::Backtrace as core::default::Default>::default::h03a8d770395d927e
   2:     0x555f07696b59 - backtrace::capture::Backtrace::new::h2eb1c11c92f206be
   3:     0x555f07695c96 - panic_hook::gen_panic_msg::h0d1944a863be6686
   4:     0x555f07695a71 - panic_hook::set_with::{{closure}}::hb98419ca46d4e249
   5:     0x555f0770b206 - std::panicking::rust_panic_with_hook::hde420d6fd4455550
                        at libstd/panicking.rs:480
   6:     0x555f0770ad51 - std::panicking::continue_panic_fmt::h8f394f3c578bcc76
                        at libstd/panicking.rs:390
   7:     0x555f0770ac35 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x555f077547cc - core::panicking::panic_fmt::hca5dc4e8b320bc56
                        at libcore/panicking.rs:77
   9:     0x555f07754842 - core::option::expect_failed::hb2b5d5a53baf7df0
                        at libcore/option.rs:1008
  10:     0x555f06988e41 - tokio_core::reactor::Core::run::h9330eac3125e2738
  11:     0x555f069578d7 - igd::search::search_gateway_from_timeout::h91e6c8502cb8b890
  12:     0x555f0693c4f1 - ethcore_network_devp2p::ip_utils::map_external_address::h193e84f5bad30475
  13:     0x555f0690124a - <ethcore_network_devp2p::host::Host as ethcore_io::IoHandler<ethcore_network::NetworkIoMessage>>::message::h2d8ccbd5a94ad9fc
  14:     0x555f068e6e8d - ethcore_io::worker::Worker::do_work::h998ecb06c425bacd
  15:     0x555f0692360f - ethcore_io::worker::Worker::new::{{closure}}::{{closure}}::hcbf39482da5efa9f
  16:     0x555f0692903c - <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::hd55d973989b8d278
  17:     0x555f068ed43c - futures::task_impl::std::set::h1d6d5567dc928dba
  18:     0x555f068d9543 - <std::thread::local::LocalKey<T>>::with::ha78225fc885ef42e
  19:     0x555f06928486 - <tokio_current_thread::Entered<'a, P>>::block_on::h50f8abd6b0103cce
  20:     0x555f068d8b61 - <std::thread::local::LocalKey<T>>::with::h078b513f102197c3
  21:     0x555f068d9368 - <std::thread::local::LocalKey<T>>::with::ha77f6ab1a7f5424b
  22:     0x555f068d8fc4 - <std::thread::local::LocalKey<T>>::with::h9438db5627f077d7
  23:     0x555f068d987b - <std::thread::local::LocalKey<T>>::with::hbc71b76579a7c8c6
  24:     0x555f0691f065 - tokio::runtime::current_thread::runtime::Runtime::block_on::hb5d7bf8c25fd6184
  25:     0x555f06912abc - tokio::runtime::current_thread::block_on_all::h6545996fa7c61142
  26:     0x555f068e7e64 - std::sys_common::backtrace::__rust_begin_short_backtrace::h18814fd682bd2738
  27:     0x555f06935956 - std::panicking::try::do_call::h19bac28102eb36bf
  28:     0x555f0771d3e9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  29:     0x555f068eb057 - <F as alloc::boxed::FnBox<A>>::call_box::h16f05c9a896fab08
  30:     0x555f0770769d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::h9d902c911a417e39
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h44127e03e78ca137
                        at libstd/sys_common/thread.rs:24
  31:     0x555f076f2255 - std::sys::unix::thread::Thread::new::thread_start::h8f17b97f2223146c
                        at libstd/sys/unix/thread.rs:90
  32:     0x7fe1239f1a9c - start_thread
  33:     0x7fe123905b22 - clone
  34:                0x0 - <unknown>

Thread 'IO Worker #3' panicked at 'cannot recursively call into `Core`', libcore/option.rs:1008

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

zsh: abort (core dumped)  ./parity --no-warp
```

**Comment by jwasinger** [comment]
Is this intermittent?  I can't reproduce it..

**Comment by 5chdn** [comment]
It happens randomly. Didn't figure out how to reproduce it yet

**Comment by 5chdn** [comment]
https://github.com/paritytech/parity-ethereum/pull/10144

**Comment by 5chdn** [comment]
closed upstream
